export const translations = {
    hero: {
        en: {
            text: "Turn Long Videos Into Viral Shorts Automatically",
            sub: "Paste a YouTube link. Our AI finds the best moments, adds captions, and creates ready-to-post Shorts."
        },
        ur: {
            text: "Lambi Videos Ko Automatic Viral Shorts Mein Badlein",
            sub: "YouTube link paste karein. AI best moments pick karta hai, captions add karta hai aur Shorts ready karta hai."
        },
        ps: {
            text: "Loye Videos Pa Automatic Viral Shorts Bandal",
            sub: "YouTube link paste kawa. AI best moments select kai, captions add kai, ao Shorts tayar kai."
        }
    },
    input: {
        en: { placeholder: "Paste YouTube Link (e.g. youtu.be/...)", button: "Generate Shorts", loading: "Finding Viral Moments...", error: "Please enter a valid YouTube URL" },
        ur: { placeholder: "YouTube Link Paste Karein...", button: "Shorts Generate Karein", loading: "Viral Moments Dhoond Raha Hai...", error: "Baraye karam durust YouTube link darj karein" },
        ps: { placeholder: "YouTube Link Paste Kawa...", button: "Shorts Generate Kai", loading: "Viral Moments Latawo...", error: "Meherbani okrei sam YouTube link paste kai" }
    },
    features: {
        ai: {
            en: { title: "AI Finds Viral Moments", desc: "Our AI scans the video to find the most engaging 20-45s clips." },
            ur: { title: "AI Viral Moments Dhoondta Hai", desc: "Hamara AI video scan karke sab se behtareen clips nikalta hai." },
            ps: { title: "AI Viral Moments Gori", desc: "Zmonga AI video gori ao engagaing clips raobasi." }
        },
        captions: {
            en: { title: "Auto Captions & Animations", desc: "Accurate subtitles with 5+ premium animation styles." },
            ur: { title: "Khudkaar Captions aur Animations", desc: "Behtareen subtitles aur 5+ animation styles ke saath." },
            ps: { title: "Automatic Captions ao Animations", desc: "Sahi subtitles ao 5+ animation styles sara." }
        },
        format: {
            en: { title: "9:16 Shorts Ready", desc: "Perfect vertical format for TikTok, Reels, and YouTube Shorts." },
            ur: { title: "9:16 Shorts Tayyar", desc: "TikTok, Reels aur YouTube Shorts ke liye mukammal vertical format." },
            ps: { title: "9:16 Shorts Tayar", desc: "TikTok, Reels ao YouTube Shorts lapara sam vertical format." }
        }
    },
    showcase: {
        title: {
            en: "See Real Shorts Generated by ReVid",
            ur: "ReVid Ke Banaye Hue Real Shorts Dekhein",
            ps: "Da ReVid Pa Lasa Jor Shaway Real Shorts Gorai"
        },
        labels: {
            original: { en: "Original Long Video", ur: "Asli Lambi Video", ps: "Asli Ogda Video" },
            generated: { en: "AI Generated Short", ur: "AI Se Bana Short", ps: "AI Jor Karay Short" }
        },
        ai_tags: {
            detected: { en: "AI detected viral moment", ur: "AI ne viral lamha dhoonda", ps: "AI viral waqt waledo" },
            captions: { en: "Auto captions generated", ur: "Khudkaar captions lagaye", ps: "Auto captions jor shwal" },
            format: { en: "Converted to 9:16", ur: "9:16 mein tabdeel kiya", ps: "9:16 ta badal sho" }
        }
    },
    flow: {
        paste: { en: "Paste YouTube Link", ur: "YouTube Link Lagayein", ps: "YouTube Link Past Kai" },
        ai: { en: "AI Finds Viral Clip", ur: "AI Clip Dhoondta Hai", ps: "AI Clip Gori" },
        ready: { en: "Ready-to-Post Short", ur: "Post Ke Liye Tayyar", ps: "Post Ta Tayyar" }
    }
} as const;
